version: '2'

services:
  frontend:
    build: ./client
    volumes:
      - '/usr/src/app/node_modules'
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      - NODE_ENV=production
      - NODE_PORT=8080
    command: "pm2-docker server.js"
