version: '2'

services:
  frontend:
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - '/usr/src/app/node_modules'
    ports:
      - '127.0.0.1:8080:8080'
    command: "pm2-docker server.js"
    depends_on:
      - web
  web:
    restart: always
    build: ./web
    ports:
      - "127.0.0.1:8000:8000"
    command: "/usr/local/bin/gunicorn -w 2 -b :8000 wsgi:app"

